apiVersion: v1
kind: PersistentVolume
metadata:
  name: powerdns-master-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  cinder:
    fsType: xfs
    volumeID: 25579a98-e511-45b2-9c68-7461c49f88c2
