apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeName: powerdns-master-pv
