apiVersion: v1
kind: PersistentVolume
metadata:
  name: bis-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8sinfnfs1
    path: /opt/k8s_infra/bis_config
    readOnly: yes