apiVersion: v1
kind: Service
metadata:
  labels:
    name: jenkins
  name: jenkins-service
  namespace: default
spec:
  type: NodePort
  selector:
    name: "jenkins-master"
  ports:
  - port: 8080
    name: http
    nodePort: 8180
    targetPort: 8080
