apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-master
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins-master
      labels:
        name: jenkins-master
    spec:
      containers:
      - name: jenkins-master
        image: jenkinsci/jenkins:2.0-beta-1
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-master
          mountPath: "/var/jenkins_home"
      volumes:
        - name: jenkins-master
          nfs:
            server: k8sinfnfs1
            path: "/opt/k8s_infra/jenkins_master"
            readOnly: false
