apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v11
  namespace: default
  labels:
    app: kube-dns
    version: v11
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    app: kube-dns
    version: v11
  template:
    metadata:
      labels:
        app: kube-dns
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      hostNetwork: true
      containers:
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.14
        env:
        - name: KUBERNETES_RO_SERVICE_HOST
          value: "10.100.1.210"
        - name: KUBERNETES_RO_SERVICE_PORT
          value: "8080"
        - name: KUBERNETES_API_PROTOCOL
          value: "http"
        command: [
          "/kube2sky",
          "--etcd-server=http://10.100.1.210:2379",
          "--domain=lite.local",
          "--kube-master-url=http://10.100.1.210:8080",
        ]
      - name: skydns
#        image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c
        image: kubernetes/skydns
        env:
        - name: ETCD_MACHINES
          value: "http://10.100.1.210:2379"
        - name: SKYDNS_DOMAIN
          value: "lite.local"
        - name: SKYDNS_NAMESERVERS
          value: "10.100.100.3:53"
        - name: SKYDNS_ADDR
          value: "0.0.0.0:53"
        command: [
          "/skydns",
          "-domain=lite.local",
        ]
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      dnsPolicy: Default