apiVersion: v1
kind: Service
metadata:
  name: kube-dns
spec:
  ports:
  - port: 53
    name: dns-udp
    protocol: UDP
    targetPort: 53
  - port: 53
    name: dns-tcp
    protocol: TCP
    targetPort: 53
  clusterIP: 10.254.1.1
  selector:
    app: kube-dns