apiVersion: v1
kind: Service
metadata:
  labels:
    name: docker-registry-service
  name: docker-registry-service
  namespace: default
spec:
  type: NodePort
  selector:
    name: "docker-registry"
  ports:
  - port: 5000
    name: http
    nodePort: 5000
    targetPort: 5000
