---
# Copyright (c) 2016, Department for Business, Energy & Industrial Strategy
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL BIS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

- name: Create the golden host
  os_server:
    name: ukbliteep01.int.licensing.service.trade.gov.uk
    image: rhel7
    flavor: t1.medium
    key_name: justin_cook
    timeout: 200
    auto_ip: yes
    security_groups: 
      - vpn
      - external_ssh
    nics:
      - port-name: dmzport11
    meta:
      hostname: ukbliteep01.int.licensing.service.trade.gov.uk

- name: Create IPA servers
  os_server:
    name: "{{ item.name }}"
    image: rhel7
    flavor: t1.medium
    key_name: justin_cook
    timeout: 200
    auto_ip: no
    security_groups:
      - mgmt_nodes
      - remote_repositories
      - ipa_server
    nics:
      - port-name: mgmtport1{{ item.count }}
    meta:
      hostname: "{{ item.name }}"
  with_items:
    - { name: 'ukbliteipa01.int.licensing.service.trade.gov.uk', count: 1 }
    - { name: 'ukbliteipa02.int.licensing.service.trade.gov.uk', count: 2 }

- name: Create management OpenShift instances
  os_server:
    name: "{{ item.name }}"
    image: rhel7
    flavor: m1.small
    key_name: justin_cook
    timeout: 200
    auto_ip: no
    nics:
      - port-name: mgmtport2{{ item.count }}
    meta:
      hostname: "{{ item.name }}"
  with_items:
    - { name: 'ukblitemom01.int.licensing.service.trade.gov.uk', count: 1 }
    - { name: 'ukblitemon01.int.licensing.service.trade.gov.uk', count: 2 }
    - { name: 'ukblitemon02.int.licensing.service.trade.gov.uk', count: 3 }

- name: Create app OpenShift instances
  os_server:
    name: "{{ item.name }}"
    image: rhel7
    flavor: m1.small
    key_name: justin_cook
    timeout: 200
    auto_ip: no
    nics:
      - port-name: appport2{{ item.count }}
    meta:
      hostname: "{{ item.name }}"
  with_items:
    - { name: 'ukbliteaom01.int.licensing.service.trade.gov.uk', count: 1 }
    - { name: 'ukbliteaon01.int.licensing.service.trade.gov.uk', count: 2 }
    - { name: 'ukbliteaon02.int.licensing.service.trade.gov.uk', count: 3 }
