---
# Copyright (c) 2016, Department for Business, Energy & Industrial Strategy
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL BIS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

- name: Install git and bc
  yum: name={{ item }} state=latest
  with_items:
    - git
    - bc

- name: Checkout Letsencrypt
  git: repo=https://github.com/letsencrypt/letsencrypt.git
       dest=/opt/letsencrypt

- name: Stop haproxy
  service: name=haproxy state=stopped

- name: Run letsencrypt
  command: >
    /opt/letsencrypt/letsencrypt-auto --standalone --agree-tos 
    certonly --standalone-supported-challenges http-01
    -d {{ domains[0] }} -d {{ domains[1] }}
    creates=/etc/letsencrypt/live/{{ domains[0] }}/fullchain.pem

- name: Create combined certfile
  command: >
    cat /etc/letsencrypt/live/{{ domains[0] }}/fullchain.pem 
    /etc/letsencrypt/live/{{ domains[0] }}/privkey.pem > 
    /etc/haproxy/certs/{{ domains[0] }}.pem
    creates=/etc/haproxy/certs/{{ domains[0] }}.pem

- name: Secure the cert
  file: path=/etc/haproxy/certs mode=go-rwx recurse=yes

- name: Fetch the cert
  fetch: src=/etc/haproxy/certs/{{ domains[0] }}.pem 
         dest=/tmp/{{ domains[0] }}.pem

