apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-s2i-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: jenkins-s2i-master-pv
