apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-s2i-master-pvc
  labels:
    name: jenkins-s2i-master-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: jenkins-s2i-master-pv
