
- hosts: localhost
  tasks:
  - name: Change the dmz network DHCP to provide internal DNS
    os_subnet:
      name: dmz1subnet
      network_name: dmz
      cidr: 10.100.254.0/24
      dns_nameservers:
        - 10.100.100.11
        - 10.100.100.12
  - name: Change the mgmt network DHCP to provide internal DNS
    os_subnet:
      name: mgmt1subnet
      network_name: mgmt
      cidr: 10.100.100.0/24
      dns_nameservers:
        - 10.100.100.11
        - 10.100.100.12
  - name: Change the app network DHCP to provide internal DNS
    os_subnet:
      name: app1subnet
      network_name: app
      cidr: 10.100.1.0/24
      dns_nameservers:
        - 10.100.100.11
        - 10.100.100.12
  - name: Change the svc network DHCP to provide internal DNS
    os_subnet:
      name: svc1subnet
      network_name: svc
      cidr: 10.100.20.0/24
      dns_nameservers:
        - 10.100.100.11
        - 10.100.100.12
