ipaserver_base_command: ipa-server-install -U 
ipaserver_configure_ssh: True
ipaserver_configure_sshd: True
ipaserver_dns_forwarder: False
ipaserver_domain: lite.bis.gov.uk
ipaserver_hbac_allow: True
ipaserver_idstart: 5000
ipaserver_idmax: False
ipaserver_mkhomedir: True
ipaserver_packages:
  - ipa-server-dns
ipaserver_realm: LITE.BIS.GOV.UK
ipaserver_setup_dns: True
ipaserver_setup_ntp: True
ipaserver_ssh_trust_dns: True
ipaserver_ui_redirect: True
ipaserver_manage_firewalld: True
